### ISSUE TITLE
大佬，你改了那些代码实现了阅读共存啊？

### ISSUE THREAD

**Issue by DDOS-SU** [10bits/gedoor-Build#1]
大佬，你改了那些代码实现了阅读共存啊？

**Comment by 10bits** [comment]
> 大佬，你改了那些代码实现了阅读共存啊？

#解决安装程序共存问题
sed "s/'.release'/'.releaseA'/" ./app/build.gradle -i
sed 's/.release/.releaseA/'    ./app/google-services.json -i
