### ISSUE TITLE
【BUG】软件重命名失效

### ISSUE THREAD

**Issue by ifwlzs** [10bits/gedoor-Build#10]
经过多个小时的测试和排查，在我和 @olixina 不懈努力下，找到了无法重命名的原因。

---

# 问题分析：

`gedoor-Build/action_app_custom.sh` 文件下，第十六行的判断出现了问题

`if [[ "$APP_NAME" == "legado" ]] && [[ "$SECRETS_RENAME" == "true" ]]; then`

执行判断时，前半句是对的，**后半句因为 `$SECRETS_RENAME` 变量未定义初始值，导致判断结果永远非true非false**

---

# 解决方案：

**给`$SECRETS_RENAME` 变量赋予`true`初始值**，可以看 @olixina 的修改记录

https://github.com/olixina/gedoor-Build/commit/8447fdf8b2bd89048b12ed95be7dc3e6cb894b01

**Comment by 10bits** [comment]
https://github.com/ifwlzs/gedoor-Build/settings/secrets/actions

这里增加一个secrets环境变量
> RENAME=true

**Comment by ifwlzs** [comment]
> https://github.com/ifwlzs/gedoor-Build/settings/secrets/actions
> 
> 这里增加一个secrets环境变量
> 
> > RENAME=true

请问下，`asset_path`应该填什么内容

**Comment by 10bits** [comment]
apk路径，脚本会自动查找，如果有就上传release
