### ISSUE TITLE
建议贴一下仓库设置

### ISSUE THREAD

**Issue by honchenc** [10bits/gedoor-Build#11]
@10bits 能不能把[https://github.com/10bits/gedoor-Build/settings/secrets/actions](https://github.com/10bits/gedoor-Build/settings/secrets/actions) 截图贴一下 试了几次都达不到想要的效果

**Comment by 10bits** [comment]
![2021-12-18_134528](https://user-images.githubusercontent.com/2499251/146630834-76deb242-3fd9-4737-be65-c9e809577f71.png)
