### ISSUE TITLE
呼叫一下

### ISSUE THREAD

**Issue by woshishiq1** [10bits/gedoor-Build#18]
能增加打包legado_lollipop吗？感谢

**Comment by 10bits** [comment]
已支持，请Fork更新脚本，你可以在Actions运行LegadoCustom，默认打包legado_lollipop

**Comment by nobk** [comment]
@10bits  是不是自动构建失败了？两周前就不更新了

**Comment by 10bits** [comment]
> @10bits 是不是自动构建失败了？两周前就不更新了

由于部分用户滥用导致github抽风，先凑合用吧
> https://github.com/coolsnowwolf/lede/issues/7757

**Comment by kylin59** [comment]
> 已支持，请Fork更新脚本，你可以在Actions运行LegadoCustom，默认打包legado_lollipop

已经不行了

**Comment by 10bits** [comment]
官方默认打包最低支持Lollipop了，Google版去除了，不用纠结这些了
