### ISSUE TITLE
建议构建时，将play专属功能限制去掉

### ISSUE THREAD

**Issue by dianso** [10bits/gedoor-Build#5]
建议构建时，将play专属功能限制去掉

**Comment by 10bits** [comment]
ok

**Comment by dianso** [comment]
> ok

我看到最新的似乎构建失败了

**Comment by 10bits** [comment]
没有啊，那是定时任务，有新版本才会构建
https://github.com/10bits/gedoor-Build/actions/runs/520601888

**Comment by GYQ-18** [comment]
> 建议构建时，将play专属功能限制去掉

这样不好吧，毕竟人家那是收费的
